MODEL:
  MODEL_NAME: yolov4-p6
  MODEL_PATH: model_data/model_weights/yolov4-p6.h5
  BACKBONE:
    NAME: CSPDarkNet
    BASE: 8 
    ATTENTION_TYPE: None

LOSS:
  USE_LABEL_SMOOTHING: True
  USE_GIOU_LOSS: False
  USE_DIOU_LOSS: False
  USE_CIOU_LOSS: True

INPUT:
  SIZE_TRAIN: [ 640,640 ]
  SIZE_VAL: [ 640,640 ]

SOLVER:
  OPITIMIZER_NAME: Adam
  EPOCH: 500
  LEARNING_RATE: 0.001
  BATCH_SIZE: 8

  SCHED:
    NAME: ReduceLROnPlateau
    FACTOR: 0.1
    PATIENCE: 2

  EARLYSTOPPING:
    MIN_DELTA: 1e-6
    PATIENCE: 20

LOGS_DIR: logs/
CHECKPOINTS_DIR: checkpoints/
