MODEL:
  MODEL_NAME: yolov3-tiny
  MODEL_PATH: None

LOSS:
  USE_LABEL_SMOOTHING: False
  USE_GIOU_LOSS: False
  USE_DIOU_LOSS: False
  USE_CIOU_LOSS: False

INPUT:
  SIZE_TRAIN: [ 416,416 ]
  SIZE_VAL: [ 416,416 ]

SOLVER:
  OPITIMIZER_NAME: Adam
  EPOCH: 500
  LEARNING_RATE: 0.001
  BATCH_SIZE: 8

  SCHED:
    NAME: ReduceLROnPlateau
    FACTOR: 0.1
    PATIENCE: 2

  EARLYSTOPPING:
    MIN_DELTA: 1e-6
    PATIENCE: 20

LOGS_DIR: logs/
CHECKPOINTS_DIR: checkpoints/